# Bot configuration constants
BOT_TOKEN = "NDgzNDY2MDE5MDM0MTAzODA5.DnTbdA.RRfdZH7XFVFKwFmPc6hqTUzRNRk"

BOT_PREFIX = "Travis"
BOT_DESCRIPTION = ""
BOT_SEARCH_STRING = "Travis"

KNOWN_GAMES = {"Mastermind": 1, "Checkers": 2}

SR_ENERGY_THRESHOLD = 150
SR_DYNAMIC_ENERGY_THRESHOLD = True

